# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-12-05 11:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cameraName', models.CharField(max_length=256, verbose_name='摄像头名称')),
                ('cameraLocation', models.CharField(max_length=256, verbose_name='摄像头位置')),
                ('cameraLat', models.CharField(max_length=24, verbose_name='纬度')),
                ('cameraLon', models.CharField(max_length=24, verbose_name='经度')),
                ('c_ip', models.CharField(max_length=24, null=True, verbose_name='摄像头ip地址')),
                ('c_username', models.CharField(max_length=100, null=True, verbose_name='摄像头用户名')),
                ('c_password', models.CharField(max_length=100, null=True, verbose_name='摄像头密码')),
                ('c_token', models.CharField(max_length=24, null=True, verbose_name='摄像头token')),
                ('c_detectStatus', models.IntegerField(choices=[(0, 'close'), (1, 'open')], default=0, verbose_name='摄像头检测状态')),
            ],
            options={
                'verbose_name_plural': '摄像头信息',
                'verbose_name': '摄像头信息',
            },
        ),
        migrations.CreateModel(
            name='CameraRealtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cameraid', models.CharField(max_length=10, verbose_name='摄像头ID')),
                ('c_x', models.CharField(blank=True, max_length=10, null=True, verbose_name='矩形框x')),
                ('c_y', models.CharField(blank=True, max_length=10, null=True, verbose_name='矩形框y')),
                ('c_w', models.CharField(blank=True, max_length=10, null=True, verbose_name='矩形框w')),
                ('c_h', models.CharField(blank=True, max_length=10, null=True, verbose_name='矩形框h')),
                ('c_threshold', models.CharField(blank=True, max_length=10, null=True, verbose_name='检测阈值')),
                ('imgurl', models.CharField(max_length=100, null=True, verbose_name='图片url')),
                ('faceid', models.CharField(max_length=10, verbose_name='人员ID')),
            ],
            options={
                'verbose_name_plural': '实时监控数据',
                'verbose_name': '实时监控数据',
            },
        ),
        migrations.CreateModel(
            name='CameraStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamUrl', models.URLField(null=True, unique=True, verbose_name='视频地址')),
                ('streamTime', models.CharField(blank=True, max_length=256, null=True, verbose_name='流time')),
                ('streamFps', models.CharField(blank=True, max_length=256, null=True, verbose_name='流fps')),
                ('streamStatus', models.CharField(blank=True, max_length=256, null=True, verbose_name='流status')),
                ('startTime', models.CharField(blank=True, max_length=256, null=True, verbose_name='流time')),
                ('label', models.CharField(blank=True, max_length=256, null=True, verbose_name='时间')),
                ('cameraId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Camera')),
            ],
            options={
                'verbose_name_plural': '录像信息',
                'verbose_name': '录像信息',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceid', models.CharField(max_length=10, verbose_name='人脸ID')),
                ('streamid', models.CharField(max_length=256, verbose_name='流ID')),
                ('timestap', models.CharField(max_length=100, verbose_name='时间戳')),
                ('time', models.FloatField(null=True, verbose_name='时间')),
                ('c_x', models.CharField(blank=True, max_length=10, null=True, verbose_name='矩形框x')),
                ('c_y', models.CharField(blank=True, max_length=10, null=True, verbose_name='矩形框y')),
                ('c_w', models.CharField(blank=True, max_length=10, null=True, verbose_name='矩形框w')),
                ('c_h', models.CharField(blank=True, max_length=10, null=True, verbose_name='矩形框h')),
                ('c_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='ip')),
                ('c_gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='检测性别')),
                ('c_age', models.CharField(blank=True, max_length=10, null=True, verbose_name='检测年龄')),
                ('c_threshold', models.CharField(blank=True, max_length=10, null=True, verbose_name='检测阈值')),
                ('url', models.CharField(max_length=100, null=True, verbose_name='流url')),
                ('imgurl', models.CharField(max_length=100, null=True, verbose_name='图片url')),
            ],
            options={
                'verbose_name_plural': '匹配信息',
                'verbose_name': '匹配信息',
            },
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('gender', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('flag', models.IntegerField(choices=[(0, 'new'), (1, 'update'), (2, 'delete')], default=0)),
                ('face_flag', models.IntegerField(choices=[(0, 'proprietor'), (1, 'temporary'), (2, 'slack'), (3, 'lost')], default=0)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '人脸数据',
                'verbose_name': '人脸数据',
            },
        ),
        migrations.CreateModel(
            name='FaceImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.URLField(null=True, verbose_name='照片地址')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Face')),
            ],
            options={
                'verbose_name_plural': '人脸图片地址',
                'verbose_name': '人脸图片地址',
            },
        ),
        migrations.CreateModel(
            name='FunctionInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=128)),
                ('method', models.CharField(max_length=32, null=True)),
                ('description', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchUp',
            fields=[
                ('person_id', models.CharField(blank=True, max_length=24, null=True, verbose_name='行人ID')),
                ('faceid', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='人脸ID')),
                ('c_threshold', models.CharField(max_length=10, verbose_name='置信度')),
                ('dec_img_url', models.CharField(max_length=100, verbose_name='检测图片地址')),
            ],
            options={
                'verbose_name_plural': '对应关系表',
                'verbose_name': '对应关系表',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('path', models.CharField(max_length=128)),
                ('icon', models.CharField(max_length=128, null=True)),
                ('mtype', models.IntegerField(null=True)),
                ('sort', models.IntegerField(null=True)),
                ('isLock', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Menu')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.FunctionInterface')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.FunctionInterface')),
            ],
        ),
        migrations.CreateModel(
            name='PersonDetect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(blank=True, max_length=24, null=True, verbose_name='流time')),
                ('c_x', models.CharField(blank=True, max_length=10, null=True, verbose_name='矩形框x')),
                ('c_y', models.CharField(blank=True, max_length=10, null=True, verbose_name='矩形框y')),
                ('c_w', models.CharField(blank=True, max_length=10, null=True, verbose_name='矩形框w')),
                ('c_h', models.CharField(blank=True, max_length=10, null=True, verbose_name='矩形框h')),
                ('c_threshold', models.CharField(blank=True, max_length=10, null=True, verbose_name='置信度')),
                ('url', models.CharField(max_length=100, verbose_name='流url')),
                ('timestap', models.CharField(max_length=100, verbose_name='时间戳')),
                ('dec_img_url', models.CharField(max_length=100, verbose_name='检测图片地址')),
            ],
            options={
                'verbose_name_plural': '行人检测信息',
                'verbose_name': '行人检测信息',
            },
        ),
        migrations.CreateModel(
            name='PersonReid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceid', models.CharField(max_length=10, verbose_name='人员ID')),
                ('streamid', models.CharField(max_length=256, verbose_name='流ID')),
                ('query_imgurl', models.CharField(max_length=100, verbose_name='检测图片地址')),
                ('timestap', models.CharField(max_length=20, verbose_name='时间戳')),
                ('c_threshold', models.CharField(max_length=10, verbose_name='置信度')),
                ('imgurl', models.CharField(max_length=100, verbose_name='top图片地址')),
                ('url', models.CharField(max_length=100, null=True, verbose_name='流url')),
                ('time', models.FloatField(null=True, verbose_name='时间')),
                ('c_x', models.CharField(blank=True, max_length=10, null=True, verbose_name='矩形框x')),
                ('c_y', models.CharField(blank=True, max_length=10, null=True, verbose_name='矩形框y')),
                ('c_w', models.CharField(blank=True, max_length=10, null=True, verbose_name='矩形框w')),
                ('c_h', models.CharField(blank=True, max_length=10, null=True, verbose_name='矩形框h')),
            ],
            options={
                'verbose_name_plural': '行人重识别',
                'verbose_name': '行人重识别',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Role')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32, null=True)),
                ('path', models.CharField(max_length=128, null=True)),
                ('component', models.CharField(max_length=128, null=True)),
                ('componentPath', models.CharField(max_length=128, null=True)),
                ('icon', models.CharField(max_length=128, null=True)),
                ('mtype', models.IntegerField(default=0)),
                ('sort', models.IntegerField(default=0)),
                ('isLock', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Route')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.FunctionInterface')),
            ],
        ),
        migrations.CreateModel(
            name='Stranger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceid', models.CharField(max_length=10, verbose_name='人脸ID')),
                ('c_gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='检测性别')),
                ('c_age', models.CharField(blank=True, max_length=10, null=True, verbose_name='检测年龄')),
                ('imgurl', models.CharField(max_length=100, null=True, verbose_name='图片url')),
            ],
            options={
                'verbose_name_plural': '陌生人脸图片地址',
                'verbose_name': '陌生人脸图片地址',
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamname', models.CharField(max_length=50, unique=True, verbose_name='流名称')),
                ('streamlocation', models.CharField(max_length=100, verbose_name='流位置')),
                ('streamurl', models.CharField(max_length=256, verbose_name='流url')),
                ('streamlat', models.CharField(blank=True, max_length=24, verbose_name='纬度')),
                ('streamlon', models.CharField(blank=True, max_length=24, verbose_name='经度')),
                ('flag', models.IntegerField(choices=[(0, 'new'), (1, 'update'), (2, 'delete')], default=0)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('streamtime', models.CharField(blank=True, max_length=256, null=True, verbose_name='流time')),
                ('streamfps', models.CharField(blank=True, max_length=256, null=True, verbose_name='流fps')),
                ('streamstatus', models.CharField(blank=True, max_length=256, null=True, verbose_name='流status')),
            ],
            options={
                'verbose_name_plural': '流信息',
                'verbose_name': '流信息',
            },
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='验证码')),
                ('mobile', models.CharField(max_length=11, verbose_name='电话')),
            ],
            options={
                'verbose_name_plural': '短信验证码',
                'verbose_name': '短信验证码',
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Role'),
        ),
        migrations.AddField(
            model_name='functioninterface',
            name='interface',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Interface'),
        ),
    ]
