# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-17 01:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('gender', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('flag', models.IntegerField(choices=[(0, 'new'), (1, 'update'), (2, 'delete')], default=0)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '人脸数据',
                'verbose_name_plural': '人脸数据',
            },
        ),
        migrations.CreateModel(
            name='FaceImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.URLField(verbose_name='照片地址')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Face')),
            ],
            options={
                'verbose_name': '人脸图片地址',
                'verbose_name_plural': '人脸图片地址',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=11, verbose_name='手机号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='验证码')),
                ('mobile', models.CharField(max_length=11, verbose_name='电话')),
            ],
            options={
                'verbose_name': '短信验证码',
                'verbose_name_plural': '短信验证码',
            },
        ),
    ]
